import dao.dao_connection
from typing import TypeVar, Generic, List

from dao.daos_read import *

account_division_dao_instance = account_division_dao()
account_group_dao_instance = account_group_dao()
account_instance_dao_instance = account_instance_dao()
account_title_dao_instance = account_title_dao()
auth_identity_dao_instance = auth_identity_dao()
auth_password_dao_instance = auth_password_dao()
auth_permission_dao_instance = auth_permission_dao()
auth_request_dao_instance = auth_request_dao()
auth_role_dao_instance = auth_role_dao()
auth_token_dao_instance = auth_token_dao()
client_instance_dao_instance = client_instance_dao()
country_dao_instance = country_dao()
currency_dao_instance = currency_dao()
entry_final_dao_instance = entry_final_dao()
entry_save_dao_instance = entry_save_dao()
event_channel_dao_instance = event_channel_dao()
event_instance_dao_instance = event_instance_dao()
event_subscription_dao_instance = event_subscription_dao()
invoice_instance_dao_instance = invoice_instance_dao()
notification_instance_dao_instance = notification_instance_dao()
project_budget_dao_instance = project_budget_dao()
project_group_dao_instance = project_group_dao()
project_instance_dao_instance = project_instance_dao()
project_milestone_dao_instance = project_milestone_dao()
system_attribute_dao_instance = system_attribute_dao()
system_change_dao_instance = system_change_dao()
system_exception_dao_instance = system_exception_dao()
system_instance_dao_instance = system_instance_dao()
system_object_dao_instance = system_object_dao()
system_setting_dao_instance = system_setting_dao()
system_state_dao_instance = system_state_dao()
