# auto-generated - v_definition_python_services_object - START at 2024-03-30 03:45:14.272376+01
from service.service_object import *


class service_list_base(base_object):
    all_services: list[service_base] = []
    account_service_inst = account_service()
    account_division_service_inst = account_division_service()
    account_division_template_service_inst = account_division_template_service()
    account_group_service_inst = account_group_service()
    account_hierarchy_service_inst = account_hierarchy_service()
    account_rate_service_inst = account_rate_service()
    account_skill_service_inst = account_skill_service()
    account_team_service_inst = account_team_service()
    account_title_service_inst = account_title_service()
    account_title_responsibility_service_inst = account_title_responsibility_service()
    account_type_service_inst = account_type_service()
    audit_change_service_inst = audit_change_service()
    audit_type_service_inst = audit_type_service()
    auth_attempt_service_inst = auth_attempt_service()
    auth_identity_service_inst = auth_identity_service()
    auth_identity_tenant_service_inst = auth_identity_tenant_service()
    auth_key_service_inst = auth_key_service()
    auth_key_type_service_inst = auth_key_type_service()
    auth_password_service_inst = auth_password_service()
    auth_password_current_service_inst = auth_password_current_service()
    auth_password_rule_service_inst = auth_password_rule_service()
    auth_permission_service_inst = auth_permission_service()
    auth_request_service_inst = auth_request_service()
    auth_role_service_inst = auth_role_service()
    auth_role_uri_service_inst = auth_role_uri_service()
    auth_session_service_inst = auth_session_service()
    auth_sso_service_inst = auth_sso_service()
    auth_token_service_inst = auth_token_service()
    calendar_account_service_inst = calendar_account_service()
    calendar_approval_service_inst = calendar_approval_service()
    calendar_approval_type_service_inst = calendar_approval_type_service()
    calendar_event_service_inst = calendar_event_service()
    calendar_event_group_service_inst = calendar_event_group_service()
    calendar_event_type_service_inst = calendar_event_type_service()
    calendar_type_service_inst = calendar_type_service()
    client_service_inst = client_service()
    client_account_service_inst = client_account_service()
    client_country_service_inst = client_country_service()
    client_payment_service_inst = client_payment_service()
    client_role_service_inst = client_role_service()
    client_status_service_inst = client_status_service()
    client_type_service_inst = client_type_service()
    connection_engine_service_inst = connection_engine_service()
    connection_host_service_inst = connection_host_service()
    connection_user_service_inst = connection_user_service()
    country_service_inst = country_service()
    currency_service_inst = currency_service()
    event_acknowledge_service_inst = event_acknowledge_service()
    event_channel_service_inst = event_channel_service()
    event_channel_type_service_inst = event_channel_type_service()
    event_instance_service_inst = event_instance_service()
    event_notification_service_inst = event_notification_service()
    event_observer_service_inst = event_observer_service()
    event_subscription_service_inst = event_subscription_service()
    event_template_service_inst = event_template_service()
    event_type_service_inst = event_type_service()
    invoice_action_service_inst = invoice_action_service()
    invoice_action_type_service_inst = invoice_action_type_service()
    invoice_category_service_inst = invoice_category_service()
    invoice_entry_service_inst = invoice_entry_service()
    invoice_flow_service_inst = invoice_flow_service()
    invoice_flow_state_service_inst = invoice_flow_state_service()
    invoice_instance_service_inst = invoice_instance_service()
    invoice_status_service_inst = invoice_status_service()
    invoice_type_service_inst = invoice_type_service()
    monitor_service_inst = monitor_service()
    monitor_run_service_inst = monitor_run_service()
    monitor_type_service_inst = monitor_type_service()
    period_service_inst = period_service()
    process_service_inst = process_service()
    process_run_service_inst = process_run_service()
    process_type_service_inst = process_type_service()
    project_account_service_inst = project_account_service()
    project_budget_service_inst = project_budget_service()
    project_group_service_inst = project_group_service()
    project_instance_service_inst = project_instance_service()
    project_milestone_service_inst = project_milestone_service()
    project_type_service_inst = project_type_service()
    report_service_inst = report_service()
    report_content_type_service_inst = report_content_type_service()
    report_format_service_inst = report_format_service()
    report_run_service_inst = report_run_service()
    report_status_service_inst = report_status_service()
    report_type_service_inst = report_type_service()
    storage_service_inst = storage_service()
    storage_connection_service_inst = storage_connection_service()
    storage_query_service_inst = storage_query_service()
    storage_type_service_inst = storage_type_service()
    synchronization_service_inst = synchronization_service()
    synchronization_run_service_inst = synchronization_run_service()
    synchronization_type_service_inst = synchronization_type_service()
    system_attribute_service_inst = system_attribute_service()
    system_database_service_inst = system_database_service()
    system_exception_service_inst = system_exception_service()
    system_instance_service_inst = system_instance_service()
    system_license_service_inst = system_license_service()
    system_lock_service_inst = system_lock_service()
    system_module_service_inst = system_module_service()
    system_query_service_inst = system_query_service()
    system_request_service_inst = system_request_service()
    system_setting_service_inst = system_setting_service()
    system_setting_account_service_inst = system_setting_account_service()
    system_state_service_inst = system_state_service()
    system_table_service_inst = system_table_service()
    system_thread_service_inst = system_thread_service()
    system_version_service_inst = system_version_service()
    tenant_service_inst = tenant_service()
    tenant_account_service_inst = tenant_account_service()
    tenant_category_service_inst = tenant_category_service()
    tenant_country_service_inst = tenant_country_service()
    tenant_license_service_inst = tenant_license_service()
    tenant_payment_service_inst = tenant_payment_service()
    tenant_payment_type_service_inst = tenant_payment_type_service()
    tenant_role_service_inst = tenant_role_service()
    tenant_status_service_inst = tenant_status_service()
    tenant_type_service_inst = tenant_type_service()
    time_approval_service_inst = time_approval_service()
    time_entry_service_inst = time_entry_service()
    time_entry_final_service_inst = time_entry_final_service()
    time_entry_invoice_service_inst = time_entry_invoice_service()
    time_rule_service_inst = time_rule_service()
    time_rule_client_service_inst = time_rule_client_service()
    time_submit_service_inst = time_submit_service()
    time_submit_type_service_inst = time_submit_type_service()
    def register_all_services(self):
        self.all_services.append(self.account_service_inst)
        self.all_services.append(self.account_division_service_inst)
        self.all_services.append(self.account_division_template_service_inst)
        self.all_services.append(self.account_group_service_inst)
        self.all_services.append(self.account_hierarchy_service_inst)
        self.all_services.append(self.account_rate_service_inst)
        self.all_services.append(self.account_skill_service_inst)
        self.all_services.append(self.account_team_service_inst)
        self.all_services.append(self.account_title_service_inst)
        self.all_services.append(self.account_title_responsibility_service_inst)
        self.all_services.append(self.account_type_service_inst)
        self.all_services.append(self.audit_change_service_inst)
        self.all_services.append(self.audit_type_service_inst)
        self.all_services.append(self.auth_attempt_service_inst)
        self.all_services.append(self.auth_identity_service_inst)
        self.all_services.append(self.auth_identity_tenant_service_inst)
        self.all_services.append(self.auth_key_service_inst)
        self.all_services.append(self.auth_key_type_service_inst)
        self.all_services.append(self.auth_password_service_inst)
        self.all_services.append(self.auth_password_current_service_inst)
        self.all_services.append(self.auth_password_rule_service_inst)
        self.all_services.append(self.auth_permission_service_inst)
        self.all_services.append(self.auth_request_service_inst)
        self.all_services.append(self.auth_role_service_inst)
        self.all_services.append(self.auth_role_uri_service_inst)
        self.all_services.append(self.auth_session_service_inst)
        self.all_services.append(self.auth_sso_service_inst)
        self.all_services.append(self.auth_token_service_inst)
        self.all_services.append(self.calendar_account_service_inst)
        self.all_services.append(self.calendar_approval_service_inst)
        self.all_services.append(self.calendar_approval_type_service_inst)
        self.all_services.append(self.calendar_event_service_inst)
        self.all_services.append(self.calendar_event_group_service_inst)
        self.all_services.append(self.calendar_event_type_service_inst)
        self.all_services.append(self.calendar_type_service_inst)
        self.all_services.append(self.client_service_inst)
        self.all_services.append(self.client_account_service_inst)
        self.all_services.append(self.client_country_service_inst)
        self.all_services.append(self.client_payment_service_inst)
        self.all_services.append(self.client_role_service_inst)
        self.all_services.append(self.client_status_service_inst)
        self.all_services.append(self.client_type_service_inst)
        self.all_services.append(self.connection_engine_service_inst)
        self.all_services.append(self.connection_host_service_inst)
        self.all_services.append(self.connection_user_service_inst)
        self.all_services.append(self.country_service_inst)
        self.all_services.append(self.currency_service_inst)
        self.all_services.append(self.event_acknowledge_service_inst)
        self.all_services.append(self.event_channel_service_inst)
        self.all_services.append(self.event_channel_type_service_inst)
        self.all_services.append(self.event_instance_service_inst)
        self.all_services.append(self.event_notification_service_inst)
        self.all_services.append(self.event_observer_service_inst)
        self.all_services.append(self.event_subscription_service_inst)
        self.all_services.append(self.event_template_service_inst)
        self.all_services.append(self.event_type_service_inst)
        self.all_services.append(self.invoice_action_service_inst)
        self.all_services.append(self.invoice_action_type_service_inst)
        self.all_services.append(self.invoice_category_service_inst)
        self.all_services.append(self.invoice_entry_service_inst)
        self.all_services.append(self.invoice_flow_service_inst)
        self.all_services.append(self.invoice_flow_state_service_inst)
        self.all_services.append(self.invoice_instance_service_inst)
        self.all_services.append(self.invoice_status_service_inst)
        self.all_services.append(self.invoice_type_service_inst)
        self.all_services.append(self.monitor_service_inst)
        self.all_services.append(self.monitor_run_service_inst)
        self.all_services.append(self.monitor_type_service_inst)
        self.all_services.append(self.period_service_inst)
        self.all_services.append(self.process_service_inst)
        self.all_services.append(self.process_run_service_inst)
        self.all_services.append(self.process_type_service_inst)
        self.all_services.append(self.project_account_service_inst)
        self.all_services.append(self.project_budget_service_inst)
        self.all_services.append(self.project_group_service_inst)
        self.all_services.append(self.project_instance_service_inst)
        self.all_services.append(self.project_milestone_service_inst)
        self.all_services.append(self.project_type_service_inst)
        self.all_services.append(self.report_service_inst)
        self.all_services.append(self.report_content_type_service_inst)
        self.all_services.append(self.report_format_service_inst)
        self.all_services.append(self.report_run_service_inst)
        self.all_services.append(self.report_status_service_inst)
        self.all_services.append(self.report_type_service_inst)
        self.all_services.append(self.storage_service_inst)
        self.all_services.append(self.storage_connection_service_inst)
        self.all_services.append(self.storage_query_service_inst)
        self.all_services.append(self.storage_type_service_inst)
        self.all_services.append(self.synchronization_service_inst)
        self.all_services.append(self.synchronization_run_service_inst)
        self.all_services.append(self.synchronization_type_service_inst)
        self.all_services.append(self.system_attribute_service_inst)
        self.all_services.append(self.system_database_service_inst)
        self.all_services.append(self.system_exception_service_inst)
        self.all_services.append(self.system_instance_service_inst)
        self.all_services.append(self.system_license_service_inst)
        self.all_services.append(self.system_lock_service_inst)
        self.all_services.append(self.system_module_service_inst)
        self.all_services.append(self.system_query_service_inst)
        self.all_services.append(self.system_request_service_inst)
        self.all_services.append(self.system_setting_service_inst)
        self.all_services.append(self.system_setting_account_service_inst)
        self.all_services.append(self.system_state_service_inst)
        self.all_services.append(self.system_table_service_inst)
        self.all_services.append(self.system_thread_service_inst)
        self.all_services.append(self.system_version_service_inst)
        self.all_services.append(self.tenant_service_inst)
        self.all_services.append(self.tenant_account_service_inst)
        self.all_services.append(self.tenant_category_service_inst)
        self.all_services.append(self.tenant_country_service_inst)
        self.all_services.append(self.tenant_license_service_inst)
        self.all_services.append(self.tenant_payment_service_inst)
        self.all_services.append(self.tenant_payment_type_service_inst)
        self.all_services.append(self.tenant_role_service_inst)
        self.all_services.append(self.tenant_status_service_inst)
        self.all_services.append(self.tenant_type_service_inst)
        self.all_services.append(self.time_approval_service_inst)
        self.all_services.append(self.time_entry_service_inst)
        self.all_services.append(self.time_entry_final_service_inst)
        self.all_services.append(self.time_entry_invoice_service_inst)
        self.all_services.append(self.time_rule_service_inst)
        self.all_services.append(self.time_rule_client_service_inst)
        self.all_services.append(self.time_submit_service_inst)
        self.all_services.append(self.time_submit_type_service_inst)
# auto-generated - v_definition_python_daos_list - END