name: timetracker

services:
  proxy:
    image: "nginx:1.26"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
  app:
    image: "timetracker-app:0.0.1"
    environment:
      - JDBC_HOST=${JDBC_HOST}
      - JDBC_NAME=${JDBC_NAME}
      - JDBC_URL=${JDBC_URL}
      - JDBC_USER_FILE=/run/secrets/db_user
      - JDBC_PASS_FILE=/run/secrets/db_pass
      - JDBC_DRIVER=${JDBC_DRIVER}
    networks:
      - timetracker
    secrets:
      - db_user
      - db_pass
    depends_on:
      - db
  db:
    image: "postgres:16.3"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER_FILE=/run/secrets/db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_pass
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - timetracker
    secrets:
      - db_user
      - db_pass


networks:
  timetracker:
    driver: bridge

volumes:
  db_data:

secrets:
  db_user:
    file: "./deploy/pg-user.secret"
  db_pass:
    file: "./deploy/pg-pass.secret"